### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by djs55** [jonludlam/ocaml-web-dashboard#10]
Since it's a user-facing thing, we don't need to include the name of a language ("ocaml") in the title.

**Comment by djs55** [comment]
Perhaps 'xwd' for 'xapi web dashboard'?

**Comment by samoht** [comment]
`xawed` is easier to say :p

**Comment by djs55** [comment]
@jonludlam renamed it to `xapi-web-dashboard` which will do for now... I quite like `xawed` though!
